name: Ejecutar-Bot

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [Ejecutar-Bot]

jobs:
  Ejecutar-Bot:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y git nodejs ffmpeg imagemagick yarn

      - name: Clonar repositorio
        run: git clone https://github.com/PeluReiv/Bot-Comedia.git

      - name: Instalar dependencias del proyecto
        run: |
          cd Bot-Comedia
          yarn install
          npm install

      - name: Ejecutar bot
        run: |
          cd Bot-Comedia
          npm start
