name: Ejecutar-Bot

on:
  workflow_dispatch:

jobs:
  Ejecutar-Bot:
    runs-on: ubuntu-latest
    steps:
      - run:  |
          git clone https://github.com/PeluReiv/Bot-Comedia.git
          cd Bot-Comedia
          sudo apt update
          sudo apt install -y git nodejs ffmpeg imagemagick yarn
          yarn install && npm install
          npm start